Travis help: explicitely require cov-core==1.15.0
so to shutdown annoying prob during coverage :

test_port_not_free (test_bad_start.Test_Scheduler_Bad_Start) ... ok
Coverage.py warning: No data was collected.
Traceback (most recent call last):
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/util.py", line 235, in _run_finalizers
    finalizer()
  File "/opt/python/2.6.9/lib/python2.6/multiprocessing/util.py", line 174, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/cov_core.py", line 20, in multiprocessing_finish
    cov.save()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coverage/control.py", line 493, in save
    self.data.write(suffix=data_suffix)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coverage/data.py", line 91, in write
    self.write_file(filename)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coverage/data.py", line 131, in write_file
    fdata = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: '/tmp/tmpOumlg1/.coverage.testing-worker-linux-027f0490-2-7771-linux-4-50667445.3028.493619'